/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_lunchonemeal_OpencvCamera */

#ifndef _Included_com_example_user_lunchonemeal_OpencvCamera
#define _Included_com_example_user_lunchonemeal_OpencvCamera
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_user_lunchonemeal_OpencvCamera_PERMISSION_REQUEST_CODE
#define com_example_user_lunchonemeal_OpencvCamera_PERMISSION_REQUEST_CODE 1L
/*
 * Class:     com_example_user_lunchonemeal_OpencvCamera
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_user_lunchonemeal_OpencvCamera_loadCascade
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_user_lunchonemeal_OpencvCamera
 * Method:    detect
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_user_lunchonemeal_OpencvCamera_detect
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
